# Configuration for Jeremy Soller

include = ["../desktop.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 8192

# Package settings
[packages]
# apps
#boxedwine = {} # not building
cosmic-term = {}
cosmic-text = {}
periodictable = {}
pixelcannon = {}
schismtracker = {}
sodium = {}

# cli
acid = {}
cleye = {}
ffmpeg6 = {}
gnu-grep = {}
lua54 = {}
nano = {}
nushell = {}
perg = {}
relibc-tests = {}
ripgrep = {}
sed = {}
shellharden = {}
xz = {}

# demos
cairodemo = {}
#cmatrix = {} # addwstr
cpal = {}
gears = {}
glutin = {}
#hematite = {} # not building
iced = {}
libcosmic = {}
orbclient = {}
osdemo = {} # does not show anything
#pathfinder = {} # not building
procedural-wallpapers-rs = {}
rodioplay = {}
rust-cairo = {}
rust-cairo-demo = {}
sdl2-gears = {}
vttest = {}
webrender = {}
winit = {}

# dev
autoconf = {}
automake = {}
cargo = {}
gcc13 = {}
gnu-binutils = {}
gnu-make = {}
nasm = {}
patch = {}
pkg-config = {}
rust = {}
rustpython = {}

# games
devilutionx = {}
dosbox = {}
eduke32 = {}
flycast = {}
freedoom = {}
gigalomania = {}
mednafen = {}
mgba = {}
neverball = {}
openjazz = {}
openjk = {}
openttd = {}
openttd-opengfx = {}
openttd-openmsx = {}
openttd-opensfx = {}
prboom = {}
redox-games = {}
#retroarch = {} # need to package cores
rs-nes = {} # need game for testing
rust64 = {} # need roms
rustual-boy = {} # need game for testing
scummvm = {} # need game for testing
sm64ex = {}
sopwith = {}
spacecadetpinball = {}
syobonaction = {}
#vice = {} # broken on new toolchain
#vvvvvv = {} # cannot find -lgcc_s

# stuff
freepats = {}
generaluser-gs = {}
intel-one-mono = {}
jeremy = {}
libc-bench = {}
noto-color-emoji = {}
timidity = {}
ttf-hack = {}
